src/nnfusion/core/kernels/cpu/cpu_kernel_emitter.cpp, src/nnfusion/core/kernels/cpu/cpu_kernel_emitter.hpp, src/nnfusion/core/kernels/cpu/eigen/pad.hpp, src/nnfusion/core/kernels/cuda_gpu/cuda_emitter.cpp, src/nnfusion/core/kernels/cuda_gpu/cuda_emitter.hpp, src/nnfusion/core/kernels/cuda_gpu/kernels/pad.cpp, src/nnfusion/core/kernels/cuda_gpu/kernels/pad.hpp, src/nnfusion/core/operators/generic_op/generic_op.hpp, src/nnfusion/core/operators/generic_op/generic_op_define/Pad.cpp, src/nnfusion/core/operators/generic_op/op_registration.cpp, src/nnfusion/engine/pass/graph/op_inplace_pass.cpp
add antares memcpy; 
add inplace annotation for pad op
=> add antares memcpy & pad op inplace annotation

thirdparty/ngraph/src/nnfusion/frontend/onnx_import/op/softmax.cpp
=> Support softmax weight in onnx frontend

src/nnfusion/engine/pass/codegen/cpu_codegen_pass.cpp, src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp, src/nnfusion/engine/pass/codegen/rocm_codegen_pass.cpp
fix bug: Compile error when set -fkernels_as_files=true in model codegen and build model code in non-root folder
=> fix bug: Compile error

README.md
=> Update readme of NNFusion

models/tensorflow/nnf_tf_freezer/convert_graph_fp16.py, models/tensorflow/nnf_tf_freezer/nnf_tf_freezer.py, models/tensorflow/nnf_tf_freezer/tf_freeze_graph_example.py
add fp16 option when freeze graph.
=> add fp16 option when freeze graph

src/nnfusion/core/kernels/cpu/eigen/convolution.cpp, src/nnfusion/core/kernels/cpu/mlas/convolution.cpp, src/nnfusion/core/kernels/cuda_gpu/cuda_cudnn.cpp, src/nnfusion/core/kernels/cuda_gpu/kernels/convolution.cpp, src/nnfusion/core/kernels/cuda_gpu/kernels/convolution.hpp, src/nnfusion/core/kernels/cuda_gpu/kernels/rocm/convolution.cpp, thirdparty/ngraph/src/nnfusion/core/operators/util/validation_util.cpp, thirdparty/ngraph/src/nnfusion/frontend/onnx_import/op/conv.hpp
* support Conv1D in convolution kernel emitter of CPU, CUDA_GPU and ROCM_GPU by converting Conv1D to Conv2D #135 
* fix data_shape check in ROCM_GPU
* fix ONNX Convolution convert
=> support Conv1D in kernel emitter

models/pytorch2onnx/ort_run_frozen.py, models/tensorflow/nnf_tf_freezer/tf_run_const_folding.py, models/tensorflow/nnf_tf_freezer/tf_run_frozen.py
* cli tool of ONNX Runtime running ONNX frozen graph
* add tf_run_frozen and tf_run_const_folding cli tools to the repo
=> update model scripts

models/pytorch2onnx/ort_run_frozen.py
* more data_types in ort_run_frozen script
* more running options in ort_run_frozen script: ONNX model format check, GraphOptimizationLevel, logger_severity
=> update ort_run_frozen script

src/nnfusion/core/kernels/cuda_gpu/kernels/depthwise_conv2d.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/DepthwiseConv2dNative.cpp, src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp
fix DepthwiseConv2d op define; deprecate the kernel emitter of DepthwiseConv2d #153
=> fix DepthwiseConv2d op define; deprecate the kernel emitter of DepthwiseConv2d

src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp
=> Check op availability when importing tf models

src/nnfusion/core/kernels/cuda_gpu/kernels/depthwise_conv2d.cpp, src/nnfusion/core/kernels/hlsl/CMakeLists.txt, src/nnfusion/core/kernels/hlsl/constant.cpp, src/nnfusion/core/kernels/hlsl/hlsl_kernel_emitter.cpp, src/nnfusion/core/kernels/hlsl/hlsl_kernel_emitter.hpp, src/nnfusion/core/kernels/hlsl/hlsl_langunit.cpp, src/nnfusion/core/kernels/hlsl/hlsl_langunit.hpp, src/nnfusion/core/kernels/hlsl/result.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/DepthToSpace.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/DepthwiseConv2dNative.cpp, src/nnfusion/engine/async_manager.cpp, src/nnfusion/engine/async_manager.hpp, src/nnfusion/engine/device/hlsl.cpp, src/nnfusion/engine/memory_allocator.cpp, src/nnfusion/engine/memory_allocator.hpp, src/nnfusion/engine/pass/codegen/base_codegen_pass.cpp, src/nnfusion/engine/pass/codegen/codegenerator.cpp, src/nnfusion/engine/pass/codegen/codegenerator_helper.cpp, src/nnfusion/engine/pass/codegen/codegenerator_helper.hpp, src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp, src/nnfusion/engine/pass/codegen/hlsl_cs_codegen_pass.cpp, src/nnfusion/engine/pass/codegen/hlsl_cs_codegen_pass.hpp, src/nnfusion/engine/pass/graph/assign_async_info_pass.cpp, src/nnfusion/engine/pass/graph/assign_async_info_pass.hpp, src/nnfusion/engine/pass/graph/op_inplace_pass.cpp, src/nnfusion/engine/pass/tensor/tensor_memory_layout.cpp, src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp, src/tools/nnfusion/templates/dxcompute/make.bat
To generate c# code for hlsl backend, users need to add flag -fhlsl_csharp_codegen.
=> hlsl cs codegen

src/nnfusion/engine/pass/graph/blockfusion/blockfusion_codegen.cpp, src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.cpp, src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.hpp, src/nnfusion/engine/pass/graph/blockfusion_pass.cpp, test/nnfusion/scripts/testcase_configs/blockfusion_tests.json
* fix blockfusion internal tensor memory allocation problem #61 
* fix MergeGroups bug in -fblockfusion_level=2 #147 
* add blockfusion tests pipeline script
=> fix BlockFusion memory allocation bug and -fblockfusion_level=2 bug

src/nnfusion/core/operators/generic_op/generic_op_define/Convolution.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/MaxPool.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/Pad.cpp
* support asymmetric padding in Pad operator Antares IR translate
* asymmetric padding check in Convolution operator Antares IR translate
* support padding (both symmetric and asymmetric) in MaxPool operator Antares IR translate
=> fix Antares IR problem

src/nnfusion/core/kernels/hlsl/hlsl_langunit.cpp, src/nnfusion/core/kernels/hlsl/hlsl_langunit.hpp, src/nnfusion/engine/pass/codegen/hlsl_cs_codegen_pass.cpp
=> fix hlsl cs codegen

models/tensorflow/nnf_tf_freezer/nnf_tf_freezer.py, src/nnfusion/core/kernels/cuda_gpu/cuda_emitter.hpp, src/nnfusion/core/kernels/hlsl/hlsl_kernel_emitter.hpp, src/nnfusion/core/operators/generic_op/generic_op_define/ApplyGradient.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/ApplyGradientDescent.cpp, src/nnfusion/frontend/tensorflow_import/util/graph_convert.cpp
1. add antares ir for ApplyGradient and ApplyGradientDescent ops
2. convert VariableV2 to Parameter(require grad) for tf format model
=> add sgd ir

src/nnfusion/frontend/onnx_import/ops_bridge.cpp, src/nnfusion/frontend/onnx_import/util/graph_convert.cpp
=> Fix onnx op availablity checker

src/nnfusion/core/kernels/cuda_gpu/cuda_helper.cpp, src/nnfusion/core/kernels/cuda_gpu/kernels/broadcast.cpp
* Fix broadcast kernel warning of `unused stride3`
* Fix no newline after `nthreads` declaration
=> fix broadcast kernel warning and newline

models/tensorflow/README.md
fix wrong url in models/tensorflow/README.md
=> fix doc error

maint/script/benchmark.sh, test/nnfusion/scripts/e2e_tests.py, test/nnfusion/scripts/evaluator/e2e_evaluator.py, test/nnfusion/scripts/perf.json, test/nnfusion/scripts/testcase_configs/naive_tests.json, test/nnfusion/scripts/testcases/__init__.py, test/nnfusion/scripts/testcases/perf_cases.py
1. Build or pull docker image;
2. ./maint/script/benchmark.sh to invoke container to run benchmark script;
- Currently, we only has one case.
Result will be like:
=========================================
GCRAZGDL0007    E2E Model report
=========================================
CUDA    naive_cases #1  perf    Succeed!,       64.485329
=> Add script & case for benchmark utility

src/nnfusion/frontend/onnx_import/util/graph_convert.cpp
Current ONNX frontend graph converter will ignore outputs in input_gnodes. This PR fixes this problem.
=> Fix missing outputs in onnx frontend convert

models/pytorch2onnx/ort_run_frozen_each_layer.py
Using ```python ort_run_frozen_each_layer.py --file xxx.onnx``` will print each operator's output in ONNX model.
=> Script for printing each operator's output in ONNX model

src/nnfusion/core/kernels/cuda_gpu/kernels/reduce.hpp
Fix the correctness issue of the GNN model
=> Fix bug and improve performance for column reduction cuda_gpu kernel

docs/Coding-Guide.md, docs/End-to-end-Test.md, src/nnfusion/engine/pass/graph/blockfusion/block_kernel_schedule.cpp
The following loop is useless which should be able to find a valid set of block executor with continuous id .
https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/pass/graph/blockfusion/block_kernel_schedule.cpp#L195
Fix some typo in docs also. 
Thanks!
=> Correct `get_ready_bes` for `RangeBlockKernelScheduler`

src/nnfusion/util/curl_request.hpp
Test the curl in image "nnfusion/cuda:10.2-cudnn7-devel-ubuntu18.04"
=> Use curl cmd line to replace libcurl

setup.py, src/python/nnfusion/__main__.py
=> No need to extract tarball after installation

artifacts/roller/script_v1/elementwise.sh, artifacts/roller/test_op_mp.py
=> fix roller script_v1 elementwise.sh

src/nnfusion/frontend/onnx_import/op/squeeze.cpp, test/python/onnx_test.py
parser.add_argument("-a", "--float_as_half", default=False)
parser.add_argument("-d", "--float_as_double", default=False)
=> onnx backend test script for fp16/64

src/nnfusion/core/kernels/kernel_emitter.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/Convert.cpp, src/nnfusion/core/operators/generic_op/generic_op_define/OneHot.cpp
1. fix mapping int64 to c long long
2. cast onehot output the same type as on/off value
3. fix cast op if boolean as the target type
=> Some fixes

src/nnfusion/core/kernels/cuda_gpu/cuda_langunit.cpp
=> meet int16 request in fp16 bloom model
