microsoft/nnfusion

artifacts/README.md

It's hard to install a deb package like ttf-mscorefonts-installer through dockefile, which need user to accept the EULA.  So we need give the user the right command to install that package.

Recommand the font to be installed

---

src/nnfusion/engine/pass/codegen/base_codegen_pass.cpp

Fixed the problem where the program would generate two identical "Constant" directories, by changing the 'cp' command to 'mv' command.

two constant fixed

---

src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.cpp
src/nnfusion/engine/pass/graph/dot_transpose_pass.cpp
src/nnfusion/engine/pass/graph/kernel_selection.cpp
src/nnfusion/engine/pass/graph/pattern_substitution.cpp
src/tools/nnfusion/kernel_db/convert_tvm.py
src/tools/nnfusion/kernel_db/cuparse.py
src/tools/nnfusion/kernel_db/insert_db.sh
src/tools/nnfusion/kernel_db/profile.py
src/tools/nnfusion/kernel_db/reparse.py

- `identifier` are now generated in a join manner to resolve this issue: https://github.com/microsoft/nnfusion/issues/30
- `__syncthreads()` are now counted by logging execution instead of static analysis to resolve known bugs related to original parser
- Default `tags` for cached kernels are now set to be an empty set
- Some other minor improvements

Identifier bug fix, patch to incompetent parser

---

src/nnfusion/engine/pass/codegen/codegen_langunit.cpp
src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp

Fixed #49 by changing the /usr/local/cuda path into a cmake variable ${CUDA_TOOLKIT_ROOT_DIR}
Also solved #66 by changing the pre-set arch command into a user editable parameter

Fix static cuda path issue

---

src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.cpp
src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.hpp
src/nnfusion/engine/pass/graph/blockfusion/blockfusion_profiler.cpp
src/nnfusion/engine/pass/graph/blockfusion/blockfusion_profiler.hpp
src/nnfusion/engine/pass/graph/blockfusion/common.hpp
src/nnfusion/engine/pass/graph/blockfusion_pass.cpp

* implement BlockFusion correctness check with profiler #110 
* -fblockfusion_check_correctness=true can enable this check and blockfusion will fallback to original execution when failure detected
* this check may cost much time, so it is disabled by default

BlockFusion correctness check

---

thirdparty/ngraph/src/nnfusion/core/operators/op_define/constant.hpp

Fixed the problem that `DataBuffer` would not broadcast a vector of string with a size of 1, which caused a failure in unit-test reported in #164 .

Fix DataBuffer

---

src/nnfusion/engine/pass/graph/blockfusion/blockfusion_codegen.cpp
src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.cpp

* fix data type problem in block_kernels dedupe of BlockFusion
* fix BlockFusion split group problem when function args exceed ROCm limitation #211

Fix BlockFusion problems in block_kernel dedupe and ROCm args limitation

---

src/nnfusion/engine/pass/graph/autodiff/backward_registry.cpp
src/nnfusion/engine/pass/graph/autodiff/backward_registry.hpp
src/nnfusion/engine/pass/graph/autodiff/parameter.cpp
src/nnfusion/engine/pass/graph/autodiff_pass.cpp
src/nnfusion/frontend/onnx_import/op/gemm.cpp
src/python/example/bert.py
src/python/example/mnist.py
src/python/example/rnn.py
src/python/nnf/trainer.py

* ONNX frontend converter supports GEMM opset_11 #226 
* add training_optimizer flag (json string format) in training, e.g., ```-ftraining_optimizer=`{"optimizer": "SGD", "learning_rate": 0.01}` ```
* RNN training example on MNIST dataset
* Performance on V100-PCIe-16GB:
* ```python src/python/example/rnn.py --backend pytorch```: 0.02820s/step
* ```python src/python/example/rnn.py --backend torchscript```: 0.01497s/step
* ```python src/python/example/rnn.py --backend nnfusion```: 0.00769s/step

RNN training example on MNIST dataset

---

src/tools/nnfusion/CMakeLists.txt

Added installation of <cub> to CMakeLists.txt, to fix the bug where NNFusion cannot find <cub> as a language unit

fix cub cmakelists installation miss

---

src/nnfusion/engine/pass/graph/blockfusion/blockfusion_optimizer.cpp

Currently, we need to skip CustomCudaKernelEmitter that has shared_memory or local_sync in BlockFusion pass. We expect to support these kernels when the new profiler is ready.

Process CustomCudaKernelEmitter in BlockFusion

---

src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp

* The mean time of the previous timer will be larger than the max time for small models due to the time measurement method:
```
Result_2110_0:
8.921487e-03 1.182089e-02 8.937405e-03 7.932202e-03 1.574193e-02 3.844393e-03 -1.505094e-02 -1.112035e-02 5.026609e-03 -8.032201e-03  .. (size = 256, ends with 1.357487e-02);
Iteration time 0.338592 ms
Iteration time 0.331904 ms
Iteration time 0.336160 ms
Iteration time 0.333568 ms
Iteration time 0.343648 ms
Summary: [min, max, mean] = [0.331904, 0.343648, 0.357389] ms
```
* This PR fixed the time measurement problem.

Fix timer for cuda codegen

---

models/pytorch2onnx/ort_run_frozen.py

* Use ```--optimized_model_filepath``` to set the output path of the optimized model.
* Use ```--graph_optimization_level``` to set the [graph optimization level](https://www.onnxruntime.ai/docs/resources/graph-optimizations.html). Note that some optimization level may introduce customized op. So, it is recommend to use ```ORT_ENABLE_BASIC``` to dump optimized model.

Support dump optimized ONNX model in ort_run_frozen script

---

src/nnfusion/engine/device/cuda.cpp
src/nnfusion/engine/device/hlsl.cpp
src/nnfusion/engine/pass/graph/CMakeLists.txt
src/nnfusion/engine/pass/graph/hlsl_required_pass.cpp
src/nnfusion/engine/pass/graph/hlsl_required_pass.hpp
src/nnfusion/engine/pass/graph/runtime_const_folding_pass.cpp
src/nnfusion/frontend/onnx_import/op/where.cpp
src/tools/nnfusion/templates/dxcompute/Direct3DWinNN/runtime/D3D12APIWrapper.cpp
src/tools/nnfusion/templates/dxcompute/Direct3DWinNN/runtime/D3D12Util.h
src/tools/nnfusion/templates/dxcompute/Direct3DXBoxNN/runtime/D3D12APIWrapper.cpp
src/tools/nnfusion/templates/dxcompute/Direct3DXBoxNN/runtime/D3D12Util.h

1. 64bit integer is already supported in cs_6_0, so we disabled the conversion from 64 to 32bit integer
2. Fix onnx converter for `Where`
3. Feed inputs in order when runtime constant folding, fix #296 
4. Support load hlsl in windows-style line endings
5. Tell DirectX OOM apart from other errors

Disable dedicated pass for hlsl and enhance antares wrapper

---

src/nnfusion/core/kernels/cpu/cpu_kernel_emitter.cpp
src/nnfusion/engine/device/cpu.cpp

* Update AntaresCpuKernelEmitter for Antares v0.2.x
* Add IRBasedFusion for GENERIC_CPU backend
* Performance could match Antares **when the compilation environments (e.g., compiler, compile flags) of the generated model code and Antares kernel tuning are the same**.
* **Not solved: Antares returns multiple kernels for an op**

Fix AntaresCpuKernelEmitter and add ir_based_fusion in GENERIC_CPU backend

---

src/nnfusion/engine/pass/graph/autodiff/range.cpp
src/nnfusion/frontend/onnx_import/onnx.cpp
src/nnfusion/frontend/onnx_import/util/graph_convert.cpp

Fix correctness problems in GNN training

---

src/python/nnfusion/__main__.py

#363 
Add `sys.exit(main())` so that the console script entry-point in the pip-installable package  will have the same behavior as when run directly ([packaging-considerations](https://docs.python.org/3/library/__main__.html#packaging-considerations)). Additionally, the return value of `os.system` is system-dependent and may shift by 8 if the signal number is zero ([os.system](https://docs.python.org/3/library/os.html#os.system)). This may cause the exit status is still 0 (low byte = signal number = 0), and therefore, I replaced it with `subprocess.call`.
> Most systems require it to be in the range 0–127, and produce undefined results otherwise. ([sys.exit](https://docs.python.org/3/library/sys.html#sys.exit))
I'd love to hear your feedback.

Fix exit status is always zero

---

src/python/nnfusion/executor.py
src/python/nnfusion/jit.py
src/python/nnfusion/jit_utils.py
src/python/nnfusion/runtime.py
test/python/test_jit.py

As discussed, we need a rule to determine whether a compiled kernel can be reused.
I believe it would be better to divide the signature into two parts:
+ To avoid collision (to generate codegen path, should be readable so that we can delete useless caches)
- Relative file path of the target function
+ allow the target function to have the same other signatures, but in a different file
- Function name with scope information, `__qualname__` 
+ allow the target function to have the same function name, but with different scopes. (e.g. inner functions with different outer functions can have the same function name)
+ To detect modification (rebuild if modified)
- export to onnx model and compare the binary
**Changed**
+ Move the arguments of input and output tensors from `__init__` to `compile` …

Add signatures to detect reusable kernel + nnf rt mem reservation + jit optional kwargs

---

models/pytorch2onnx/ort_run_frozen.py
src/nnfusion/core/operators/op_define/constant.hpp
src/nnfusion/frontend/onnx_import/core/tensor.hpp
src/nnfusion/frontend/onnx_import/onnx.cpp
src/nnfusion/frontend/onnx_import/util/util.cpp

Use CUDAExecutionProvider by default to optimize FP16 models, this can avoid unintentionaly cast all fp16 inputs/weights to fp32.

Fix FP16 codegen for ONNXmodels

---

docs/NNFusion-JIT.md
docs/README.md
src/python/nnfusion/__init__.py
src/python/nnfusion/config.py
src/python/nnfusion/executor.py
src/python/nnfusion/jit.py
src/python/nnfusion/jit_utils.py
src/python/nnfusion/runtime.py
src/python/nnfusion/utils.py
test/python/test_config.py
test/python/test_jit.py

As discussed,
**Added**
+ Support JIT for class method (as decorator and as function)
+ ```python
class Net(...):
@nnfusion.jit
def forward(...):
...
```
+ ```python
class Net(...):
def forward(...):
...
model = Net()
model.forward = nnfusion.jit(model.forward) 
```
+ Note that these two approaches are essentially different because all instances share the same JIT wrapper in the former.
+ Support JIT for class
+ is equivalent to JIT `forward`
+ ```python
@nnfusion.jit
class Net(...):
def foo(...):
...
def forward(...):
...
```
will have the same behavior as
```python
class Net(...):
def foo(...):
...
@nnfusion.jit
def forward(...):
...
```
+ Implement 3-level signature
+ ```
|-- object1-signature
|   |-- model1-hash
|   |   |-- flag1-hash
|   |   |   `-- codegen
|   |   |-- flag2-hash
| …
```

Support JIT for class and class method + nnf config + 3-lvl-signature

---

src/nnfusion/common/type/element_type.cpp
src/nnfusion/core/kernels/common_langunit.cpp
src/nnfusion/core/operators/generic_op/generic_op.hpp
src/nnfusion/core/operators/op_define/constant.hpp
src/nnfusion/frontend/onnx_import/core/tensor.hpp
src/nnfusion/frontend/onnx_import/core/value_info.hpp
src/nnfusion/frontend/onnx_import/op/cast.hpp
src/nnfusion/frontend/onnx_import/op/const_of_shape.hpp
src/nnfusion/frontend/onnx_import/op/constant.hpp
src/nnfusion/frontend/onnx_import/util/graph_convert.cpp
src/nnfusion/frontend/onnx_import/util/util.cpp
src/nnfusion/frontend/onnx_import/util/util.hpp

Refactor loading onnx constant/initializers:
1. Supported type:
-   Integer type: bool/int8/uint8/int16/uint16/int32/uint32/int64/uint64
-    Floating type: float16/float32/float64
2. Known unsupported type: complex/string/bf16
3. Forbid numeric type conversion, e.g. onnx store in int but nnfusion requires as float
4. Forbid narrowing loading, e.g. int64->int32
Update antares type mapping, antares supports only int8/16/32/64 and float16/32/64

Refactor onnx tensor loading

---

src/nnfusion/core/operators/generic_op/generic_op_define/ArgMin.cpp
test/nnfusion/inventory/arg_max.cpp
test/nnfusion/inventory/arg_min.cpp

1. fix argmax/argmin missing arguments in tensorflow import unitest.
2. fix typo in src/nnfusion/core/operators/generic_op/generic_op_define/ArgMin.cpp

fix argmax/argmin missing arguments in tensorflow import unitest 
